### ISSUE TITLE
Running CI Tests against deployment preview

### ISSUE THREAD

**Issue by ivelin** [FleekHQ/action-deploy#3]
Happy New Year, Fleek team!

I am helping OlympusDAO front end dev and have a question related to CI deployment previews.

We can see the [preview deployment URL in the PR check](https://github.com/OlympusDAO/olympus-frontend/runs/4655348146), but not sure how to use it as a trigger and parameter to a github action.

```
2021-12-29T03:06:56.956Z: You can preview this build on :
2021-12-29T03:06:56.956Z: https://bafybeiduhbnqvujhupyxroqy76riecovmyytcf76lx7naup2i7gkop4lna.on.fleek.co
```

Is there a way to run Lighthouse or E2E tests against a site deployment preview? Something similar to [this Netlify deployment preview action](https://github.com/ambianic/ambianic-ui/blob/95800b787ca4aea96624996a97679fc6a1a9ab1b/.github/workflows/lighthouse.yml#L21):

```
  lighthouse:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Wait for Netlify preview deployment of this git branch
      if: github.repository_owner == 'ambianic'
      uses: jakepartusch/wait-for-netlify-action@v1
      id: get-netlify-url
      with:
        site_name: "ambianic-pwa-dist"
        max_timeout: 180
    - name: Run Lighthouse PWA check against Netlify PR Preview
      uses: treosh/lighthouse-ci-action@v8
      with:
        urls: |
          ${{ steps.get-netlify-url.outputs.url }}
        uploadArtifacts: true # save results as an action artifacts
        temporaryPublicStorage: true # upload lighthouse report to the temporary storage
        # budgetPath: '.github/lighthouse/budget.json' # performance budgets
        configPath: '.github/lighthouse/lighthouserc-netlify-preview.json' # PWA checks
```
